package com.securecam.viewer
import android.graphics.BitmapFactory; import android.os.Bundle; import android.view.View; import android.view.WindowManager
import androidx.appcompat.app.AppCompatActivity; import com.securecam.databinding.ActivityViewerBinding; import com.securecam.ui.ConnectionActivity; import com.securecam.utils.NotificationHelper; import com.securecam.webrtc.*; import com.securecam.websocket.*
import org.webrtc.IceCandidate
class ViewerActivity : AppCompatActivity() {
    private lateinit var binding: ActivityViewerBinding
    private var roomCode=""; private var connectionType=""; private var serverUrl=""
    private var webRTCManager: WebRTCManager?=null; private var signalingClient: SignalingClient?=null; private var wsStream: WebSocketStreamManager?=null
    private var isFullscreen=false; private var connected=false
    override fun onCreate(s: Bundle?) {
        super.onCreate(s); binding=ActivityViewerBinding.inflate(layoutInflater); setContentView(binding.root)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        roomCode=intent.getStringExtra(ConnectionActivity.EXTRA_ROOM_CODE)?:""; connectionType=intent.getStringExtra(ConnectionActivity.EXTRA_CONNECTION_TYPE)?:ConnectionActivity.TYPE_WEBRTC; serverUrl=intent.getStringExtra(ConnectionActivity.EXTRA_SERVER_URL)?:""
        binding.tvRoomCode.text="Room: $roomCode"; binding.tvConnectionType.text=connectionType.uppercase(); updateStatus("Connecting…",false)
        binding.btnFullscreen.setOnClickListener{isFullscreen=!isFullscreen;if(isFullscreen){binding.controlsOverlay.visibility=View.GONE;@Suppress("DEPRECATION") window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_FULLSCREEN or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY}else{binding.controlsOverlay.visibility=View.VISIBLE;@Suppress("DEPRECATION") window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_VISIBLE}}
        binding.btnDisconnect.setOnClickListener{finish()}
        binding.remoteVideoView.setOnClickListener{val v=binding.controlsOverlay.visibility==View.VISIBLE;binding.controlsOverlay.visibility=if(v)View.GONE else View.VISIBLE}
        if(connectionType==ConnectionActivity.TYPE_WEBRTC)initWebRTC() else initWS()
    }
    private fun initWebRTC(){webRTCManager=WebRTCManager(this,false,object:WebRTCManager.WebRTCListener{override fun onLocalIceCandidate(c:IceCandidate){signalingClient?.sendIceCandidate(c.sdp,c.sdpMid,c.sdpMLineIndex)};override fun onConnectionEstablished(){runOnUiThread{connected=true;updateStatus("🟢 Live Stream",true);binding.tvWaiting.visibility=View.GONE}};override fun onConnectionFailed(){runOnUiThread{updateStatus("❌ Lost",false)}};override fun onRemoteVideoReceived(){runOnUiThread{binding.tvWaiting.visibility=View.GONE;binding.remoteVideoView.visibility=View.VISIBLE}}});webRTCManager?.initialize();webRTCManager?.initRemoteRenderer(binding.remoteVideoView)
        signalingClient=SignalingClient(serverUrl,roomCode,false,object:SignalingClient.SignalingListener{override fun onConnected(){runOnUiThread{updateStatus("⏳ Waiting…",false)}};override fun onDisconnected(){runOnUiThread{updateStatus("Disconnected",false)}};override fun onPeerJoined(){runOnUiThread{updateStatus("Camera found…",false)}};override fun onPeerLeft(){runOnUiThread{connected=false;updateStatus("⏳ Camera left…",false);binding.tvWaiting.visibility=View.VISIBLE}};override fun onOfferReceived(sdp:String){webRTCManager?.createPeerConnection(binding.remoteVideoView);webRTCManager?.setRemoteOffer(sdp){a->signalingClient?.sendAnswer(a.description)}};override fun onAnswerReceived(sdp:String){};override fun onIceCandidateReceived(c:String,m:String,i:Int){webRTCManager?.addIceCandidate(c,m,i)};override fun onError(msg:String){runOnUiThread{updateStatus("⚠️ $msg",false)}}});signalingClient?.connect()}
    private fun initWS(){wsStream=WebSocketStreamManager(serverUrl,roomCode,false,object:WebSocketStreamManager.StreamListener{override fun onConnected(){runOnUiThread{updateStatus("⏳ Waiting…",false)}};override fun onDisconnected(){runOnUiThread{updateStatus("Disconnected",false)}};override fun onPeerJoined(){runOnUiThread{updateStatus("Camera found…",false)}};override fun onPeerLeft(){runOnUiThread{updateStatus("Camera left…",false);binding.tvWaiting.visibility=View.VISIBLE}};override fun onFrameReceived(d:ByteArray){val bmp=BitmapFactory.decodeByteArray(d,0,d.size);runOnUiThread{binding.wsFrameView.setImageBitmap(bmp);binding.wsFrameView.visibility=View.VISIBLE;binding.tvWaiting.visibility=View.GONE;if(!connected){connected=true;updateStatus("🟢 Live (Relay)",true)}}};override fun onStreamInfo(w:Int,h:Int){runOnUiThread{binding.tvResolution.text="${w}×${h}";binding.tvResolution.visibility=View.VISIBLE}};override fun onMotionEventReceived(t:Long){runOnUiThread{binding.tvMotionAlert.visibility=View.VISIBLE;binding.tvMotionAlert.postDelayed({binding.tvMotionAlert.visibility=View.GONE},4000)};NotificationHelper.showMotionAlert(this@ViewerActivity,0.6f)};override fun onAiEventReceived(l:String,c:Float){runOnUiThread{binding.tvAiAlert.text="🤖 $l (${"%.0f".format(c*100)}%)";binding.tvAiAlert.visibility=View.VISIBLE;binding.tvAiAlert.postDelayed({binding.tvAiAlert.visibility=View.GONE},3000)};NotificationHelper.showObjectDetectionAlert(this@ViewerActivity,l,c)};override fun onError(m:String){runOnUiThread{updateStatus("⚠️ $m",false)}}});wsStream?.connect()}
    private fun updateStatus(m:String,c:Boolean){binding.tvStatus.text=m;binding.statusDot.setBackgroundResource(if(c)android.R.drawable.presence_online else android.R.drawable.presence_busy)}
    override fun onDestroy(){super.onDestroy();webRTCManager?.release();signalingClient?.disconnect();wsStream?.disconnect()}
}