package com.securecam.webrtc
import android.content.Context; import android.util.Log; import org.webrtc.*; import org.webrtc.audio.JavaAudioDeviceModule
class WebRTCManager(private val context:Context,private val isCamera:Boolean,private val listener:WebRTCListener) {
    private lateinit var factory:PeerConnectionFactory; private var pc:PeerConnection?=null
    private var videoTrack:VideoTrack?=null; private var audioTrack:AudioTrack?=null
    private var capturer:CameraVideoCapturer?=null; private var surfHelper:SurfaceTextureHelper?=null
    private val eglBase:EglBase=EglBase.create(); val eglBaseContext get()=eglBase.eglBaseContext
    private val iceServers=listOf(PeerConnection.IceServer.builder("stun:stun.l.google.com:19302").createIceServer(),PeerConnection.IceServer.builder("stun:stun1.l.google.com:19302").createIceServer())
    fun initialize(){PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(context).createInitializationOptions());factory=PeerConnectionFactory.builder().setAudioDeviceModule(JavaAudioDeviceModule.builder(context).createAudioDeviceModule()).setVideoEncoderFactory(DefaultVideoEncoderFactory(eglBaseContext,true,true)).setVideoDecoderFactory(DefaultVideoDecoderFactory(eglBaseContext)).createPeerConnectionFactory()}
    fun startLocalCamera(sv:SurfaceViewRenderer,back:Boolean=false){sv.init(eglBaseContext,null);sv.setMirror(!back);capturer=Camera2Enumerator(context).run{deviceNames.firstOrNull{if(back)isBackFacing(it) else isFrontFacing(it)}?.let{createCapturer(it,null)}?:createCapturer(deviceNames[0],null)};surfHelper=SurfaceTextureHelper.create("CT",eglBaseContext);val vs=factory.createVideoSource(false);capturer?.initialize(surfHelper,context,vs.capturerObserver);capturer?.startCapture(1280,720,30);videoTrack=factory.createVideoTrack("V",vs);videoTrack?.addSink(sv);audioTrack=factory.createAudioTrack("A",factory.createAudioSource(MediaConstraints()))}
    fun initRemoteRenderer(sv:SurfaceViewRenderer){sv.init(eglBaseContext,null)}
    fun createPeerConnection(remote:SurfaceViewRenderer?=null):PeerConnection?{val cfg=PeerConnection.RTCConfiguration(iceServers).apply{sdpSemantics=PeerConnection.SdpSemantics.UNIFIED_PLAN};pc=factory.createPeerConnection(cfg,object:PeerConnection.Observer{override fun onSignalingChange(s:PeerConnection.SignalingState){}; override fun onIceConnectionChange(s:PeerConnection.IceConnectionState){when(s){PeerConnection.IceConnectionState.CONNECTED->listener.onConnectionEstablished();PeerConnection.IceConnectionState.FAILED->listener.onConnectionFailed();else->{}}}; override fun onIceConnectionReceivingChange(b:Boolean){}; override fun onIceGatheringChange(s:PeerConnection.IceGatheringState){}; override fun onIceCandidate(c:IceCandidate){listener.onLocalIceCandidate(c)}; override fun onIceCandidatesRemoved(a:Array<IceCandidate>){}; override fun onAddStream(s:MediaStream){if(s.videoTracks.isNotEmpty()&&remote!=null){s.videoTracks[0].addSink(remote);listener.onRemoteVideoReceived()}}; override fun onRemoveStream(s:MediaStream){}; override fun onDataChannel(d:DataChannel){}; override fun onRenegotiationNeeded(){}; override fun onAddTrack(r:RtpReceiver,s:Array<MediaStream>){val t=r.track();if(t is VideoTrack&&remote!=null){t.addSink(remote);listener.onRemoteVideoReceived()}}});if(isCamera){pc?.addTrack(videoTrack,listOf("s"));pc?.addTrack(audioTrack,listOf("s"))};return pc}
    fun createOffer(cb:(SessionDescription)->Unit){val c=MediaConstraints();pc?.createOffer(object:SdpObserver{override fun onCreateSuccess(s:SessionDescription){pc?.setLocalDescription(object:SdpObserver{override fun onCreateSuccess(s:SessionDescription){};override fun onSetSuccess(){cb(s)};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},s)};override fun onSetSuccess(){};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},c)}
    fun setRemoteOffer(sdp:String,cb:(SessionDescription)->Unit){pc?.setRemoteDescription(object:SdpObserver{override fun onCreateSuccess(s:SessionDescription){};override fun onSetSuccess(){pc?.createAnswer(object:SdpObserver{override fun onCreateSuccess(a:SessionDescription){pc?.setLocalDescription(object:SdpObserver{override fun onCreateSuccess(s:SessionDescription){};override fun onSetSuccess(){cb(a)};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},a)};override fun onSetSuccess(){};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},MediaConstraints())};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},SessionDescription(SessionDescription.Type.OFFER,sdp))}
    fun setRemoteAnswer(sdp:String){pc?.setRemoteDescription(object:SdpObserver{override fun onCreateSuccess(s:SessionDescription){};override fun onSetSuccess(){};override fun onCreateFailure(e:String){};override fun onSetFailure(e:String){}},SessionDescription(SessionDescription.Type.ANSWER,sdp))}
    fun addIceCandidate(c:String,mid:String,idx:Int){pc?.addIceCandidate(IceCandidate(mid,idx,c))}
    fun switchCamera(){(capturer as? CameraVideoCapturer)?.switchCamera(null)}
    fun setVideoEnabled(e:Boolean){videoTrack?.setEnabled(e)}; fun setAudioEnabled(e:Boolean){audioTrack?.setEnabled(e)}
    fun release(){capturer?.stopCapture();capturer?.dispose();videoTrack?.dispose();audioTrack?.dispose();surfHelper?.dispose();pc?.close();factory.dispose();eglBase.release()}
    interface WebRTCListener{fun onLocalIceCandidate(c:IceCandidate);fun onConnectionEstablished();fun onConnectionFailed();fun onRemoteVideoReceived()}
}